### PR TITLE
Use upstream version 1.16.4

### PR DESCRIPTION
**Pull request by marians**
See https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.4 for details

### CODE REVIEW

**Comment by sslavic** [comment]
@marians 1.16.5 just came out, see https://gigantic.slack.com/archives/CGLJYN9RQ/p1585672203000500

btw, I just closed my previous attempt to update to 1.16.3 https://github.com/giantswarm/cluster-autoscaler-app/pull/16 - there's some discussion there you may find useful to get e2e tests to pass eventually

**Comment by marians** [comment]
Thank you @sslavic !

**Comment by sslavic** [comment]
@marians hope I didn't discourage you from working on the upgrade.

**Comment by marians** [comment]
It wasn't you, it was the e2e testing part. I'll take it into the team to have a more capable person get it done.

**Pull request closed without merging**
