### PR TITLE
Update to cluster-autoscaler 1.16.3

### PR DESCRIPTION
**Pull request by sslavic**

### CODE REVIEW

**Comment by sslavic** [comment]
Strange, cluster-autoscaler e2e tests pass only if `nodeSelector` for the Deployment is replaced from `kubernetes.io/role: master` to `node-role.kubernetes.io/master: ""` even though in the CI build there's a step (after kind cluster has been created and before running of the test) which labels all nodes with `kubernetes.io/role: master`

I've tried to reproduce it locally with kind 0.7.0 - without labeling Pods can't be scheduled (no matching node for the selector), with labeling of the node Pod starts. @rossf7 any thoughts?

**Comment by tfussell** [comment]
@sslavic Can you perhaps SSH to the CircleCI runner and describe the cluster-autoscaler pod to see why it's not being scheduled and to verify the node labels?

**Comment by sslavic** [comment]
Yeah, that's an idea, will try in the morning. Strange there are cluster-autoscaler container logs attached to the failed CircleCI build, so it's starting up - could be something with the tests, assertions.

**Comment by rossf7** [comment]
The test is failing because the deployment never becomes ready. From the tiller logs.

```
2020-01-22T23:53:13.30043341Z stderr F [kube] 2020/01/22 23:53:13 Deployment is not ready: kube-system/cluster-autoscaler
```

The labeling step is needed because we use different node labels to kubeadmin. I though it might be a bug with `e2ectl kubeconfig path` but it looks OK.

I'd also recommend debugging it over SSH. We need to make the tests easier to run locally which is part of the integration test changes I'm working on.

**Comment by sslavic** [comment]
Closing in favor of https://github.com/giantswarm/cluster-autoscaler-app/pull/19

**Pull request closed without merging**
