### PR TITLE
Update dependencies to Kubernetes 1.16.3 

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#7675

### CODE REVIEW

**Comment by sslavic** [comment]
This can also be removed https://github.com/giantswarm/cluster-autoscaler-app/blob/master/integration/templates/cluster_autoscaler_values.go#L6

**Comment by rossf7** [comment]
> This can also be removed 

@sslavic True but we didn't remove it from any of the other PRs.

**Comment by sslavic** [comment]
Yeah, sorry, missed it, was looking for it in the other PRs but in wrong place.

**Comment by rossf7** [comment]
@sslavic No worries and good to get this cleaned up. 👍

**Pull request merged**
